### ISSUE TITLE
External libraries not loaded

### ISSUE THREAD

**Issue by GianlucaGuarini** [WebReflection/testardo#3] opened 2014-01-24 13:26 UTC
Hi Andrea, it seems that the external libraries do not get loaded correctly
that's my simple test

``` javascript
module.exports = {
    path:'my/project/path/',
    external:[
        'http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
        'assets/vendor/jquery/jquery.js'
    ],
    test: function(sandbox, window, document) {
        var $navTrigge = sandbox.query('#main-menu .nav-trigger');
        if(Modernizr.touch){
            sandbox.dispatch($navTrigge,'click');
        }
        else {
            sandbox.dispatch($navTrigge,'touchstart');
        }

        console.log($navTrigge);
    }
};
```

![screen shot 2014-01-24 at 14 23 11](https://f.cloud.github.com/assets/879612/1994968/b1ac77ca-84fa-11e3-8739-15d5f185d9ec.png)

**Comment by WebReflection** [comment] 2014-01-24 17:45
few things got wrong here … most of them could be simplified from testardo size though 
- the path must be absolute, you are missing the initial `/`
- every test and `onoad` event will receive `sandbox` argument with `window` and `document`. This happens because every test is a new window and a new document and the same is if/when you load another page via `.load(page, callback)` … you need to access loaded libraries through the `window` reference otherwise you'll be playing with the `top` scope and no library will be injected in there in order to keep `testardo` reliable. Long story short: use `window.Modernizr` or `var Modernizr = window.Modernizr;` on top of your callback.
- I am pretty sure that local files cannot be injected so this would deb the only feature request, not a bug, you might have in here.

Please open a new ticket so that this can be pointed to others doing similar mistakes with references and stuff, thank you :-)

**Closed as completed by WebReflection** 2014-01-24 17:45 UTC

**Comment by WebReflection** [comment] 2014-01-24 18:58
OK, latest has few changes such
- you can load local files but you really need absolute paths for now
- you might even skip the web server / host part using `path: "about:blank"` per each test when/if necessary
- other minor improvements with the error handler

Cheers
